---
title: "🗓️ Session 9: Importing data"
date: "2024-05-02"
date-modified: last-modified
---

This is also one of the most underestimated topics. This session builds
upon the previous session on setting up a project environment. Now you will learn
how to import data obtained elsewhere into R. We focus on importing `.csv` files,
but with the skills acquired in this context you will face no difficulties in
importing other data types as well. 


## 👨‍🏫 Lecture Slides 

Either click on the slide area below or click 
[here](/2024Spring/material/slides/T9-DataImport.pdf) to download the slides.


```{=html}
<div class="embed-container">
  <iframe 
  src="/2024Spring/material/slides/T9-DataImport.pdf" 
  style="border: 0.5px" 
  width="80%"
  height="80%"
  ></iframe>
</div>
```

- [Data for the exercises](/2024Spring/material/fread_expls.zip)

## 🎥 Lecture videos 

All the videos are available via this [playlist](https://www.youtube.com/playlist?list=PLZDawQMrG1RK05hizCTxDROrbvdACAy0h).

::: {.callout-note collapse="true"}
## Expand to access the videos directly

```{=html}
<div class="embed-container">
<iframe width="370" height="208" src="https://www.youtube.com/embed/8MTAs3u5OR0?si=L80LA5tWMwUg7Ewk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
</div>
```

```{=html}
<div class="embed-container">
<iframe width="370" height="208" src="https://www.youtube.com/embed/7mmwaqC3qRg?si=LNU51ETVRqvSOgTY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
</div>
```

```{=html}
<div class="embed-container">
<iframe width="370" height="208" src="https://www.youtube.com/embed/GNpQKsygB30?si=M1A2hLTJkzxhvMBC" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
</div>
```

```{=html}
<div class="embed-container">
<iframe width="370" height="208" src="https://www.youtube.com/embed/L_OASuntwGs?si=417PTG3nCdmG32RQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
</div>
```

```{=html}
<div class="embed-container">
<iframe width="370" height="208" src="https://www.youtube.com/embed/mn581HEFW-Y?si=8s-MJh4WHTYAYTWB" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
</div>
```

```{=html}
<div class="embed-container">
<iframe width="370" height="208" src="https://www.youtube.com/embed/OJFa10WMVuM?si=Qlq3LJc0jyXD1SGP" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
</div>
```

```{=html}
<div class="embed-container">
<iframe width="370" height="208" src="https://www.youtube.com/embed/vuyeUB6RGVU?si=dINcsJuyHgvdNP9P" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
</div>
``` 

```{=html}
<div class="embed-container">
<iframe width="370" height="208" src="https://www.youtube.com/embed/VPUBZg97Zzo?si=Ab1rXJeeu8QaECYZ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
</div>
``` 

:::

## 📚 Mandatory Reading

- The tutorial [Importing and exporting data using data.table](/2024Spring/tutorials/importing-exporting-data/index.qmd) 

## Further Reading

TBA

## ✍️ Coursework

- Do the exercises `ProjectOrga` from the `DataScienceExercises` package

::: {.callout-tip collapse="true"}
## Quick code for starting the exercises
```{r}
#| eval: false
learnr::run_tutorial(
  name = "ProjectOrga", 
  package = "DataScienceExercises", 
  shiny_args=list("launch.browser"=TRUE))
```
:::
- Download data about the CO2 emissions for some countries of your choice from
the World Bank [website](https://data.worldbank.org/indicator/EN.ATM.CO2E.PC)
for the years 2000 to 2020. Set up an R project, save the data, import it, and
make a line graph.
    - [ZIP file](/2024Spring/material/session07-solution.zip) with a possible solution^[You can ignore the `make_co2_data.R` for now and only look at `make_co2_plot.R`.]
